version: "3.8"
services:
  mysql:
    network_mode: bridge
    restart: always 
    hostname: mysql
    container_name: mysql
    image: mysql:8.0
    
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
